packagegroup: Don't build Packetdrill on 32-bits machines
The current source code of Packetdrill does not compile on
32-bits architectures because some data type mismatch. For
example:
| run_system_call.c: In function 'cmsg_expect_eq':
| run_system_call.c:860:38: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'size_t {aka unsigned int}' [-Werror=format=]
|       "Bad len in cmsg %d: expected=%lu actual=%lu",
|                                     ~~^
|                                     %u
|       i, ecm->cmsg_len, acm->cmsg_len);

Another example:
| run_system_call.c: In function 'get_epoll_event_from_expr':
| run_system_call.c:2924:21: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
|    event->data.ptr = (void *)epollev_expr->ptr->value.num;
|                      ^

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>

(Cherry-picked from commit f3430de186aa7bc0596afca474bc4814ff6a6731)