linux: Disable sample config fragments
make -sk KBUILD_BUILD_USER=TuxBuild -C/linux -j16 ARCH=i386 HOSTCC=gcc CC="sccache gcc" O=build
In file included from /usr/include/linux/filter.h:10,
                 from ../samples/seccomp/bpf-fancy.c:12:
/usr/include/linux/types.h:5:10: fatal error: asm/types.h: No such file or directory
    5 | #include <asm/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

Signed-off-by: Naresh Kamboju <naresh.kamboju@linaro.org>

(Cherry-picked from commit f4ee9d463fb142b21d617a2483b0b647323f05ad)