packagegroup: Really fix lkft-tools-basics naming
Fixes:
  ERROR: Nothing RPROVIDES 'packagegroup-lkft-tools-basics' (but
  /oe/meta-lkft/meta/recipes-samples/packagegroups/packagegroup-lkft-tools.bb
  RDEPENDS on or otherwise requires it)
  ERROR: Required build target 'lkft-console-image' has no buildable providers.
  Missing or unbuildable dependency chain was: ['lkft-console-image',
  'packagegroup-lkft-tools', 'packagegroup-lkft-tools-basics']
introduced by edd4b329de922c3dc8a02515fa9dfb7b74a69c5f.

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>