packagegroup: Really fix lkft-tools-basics naming
Fixes:
  ERROR: Nothing RPROVIDES 'packagegroup-lkft-tools-basics' (but
  /oe/meta-lkft/meta/recipes-samples/packagegroups/packagegroup-lkft-tools.bb
  RDEPENDS on or otherwise requires it)
  ERROR: Required build target 'lkft-console-image' has no buildable providers.
  Missing or unbuildable dependency chain was: ['lkft-console-image',
  'packagegroup-lkft-tools', 'packagegroup-lkft-tools-basics']
introduced by 882474898a89326857c5825732d9487467a10919

Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>